debian-base: resolve conflict with Yocto mesa-megadriver package
The conflict is introduced by the Debian package libgtk-3-dev bringing in
libgl1-mesa-dri, and Yocto side by mesa (mesa-megadriver). This only arise
when doing a build for the machine var-som-mx93.

The easiest solution is to remove the file introducing the conflict between
the two worlds.

This will resolve the following conflict (do_rootfs stage):

Transaction Summary
====================================================================================================================================
Install  1178 Packages
Skip        1 Package

Total size: 651 M
Installed size: 2.3 G
Downloading Packages:
Running transaction check
Transaction check succeeded.
Running transaction test
Error: Transaction test error:
  file /usr/share/drirc.d/00-mesa-defaults.conf conflicts between attempted installs of mesa-megadriver-2:23.0.0-r0.armv8a and debian-base-12-r0.armv8a

Signed-off-by: Alexander Herfurtner <alexander.h@variscite.com>