debian-base: remove libwayland-dev
This will resolve a conflict with Debian debian-base and Yocto wayland package.

do_rootfs stage:
--
Error: Transaction test error:
  file /usr/share/wayland/wayland.xml conflicts between attempted installs of wayland-1.22.0.imx-r0.armv8a_mx93 and debian-base-12-r0.armv8a

Signed-off-by: Alexander Herfurtner <alexander.h@variscite.com>