debian-base: drop python3-opencv from Debian
The package python3-opencv can be theoretically provided by Debian,
but it seems not be compatible with the machine-specific libs due
to a version issue.

Debian wants libopencv*406, while Yocto provides libopencv*407.

$ python3
Python 3.11.2 (main, Mar 13 2023, 12:18:29) [GCC 12.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import cv2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: libopencv_highgui.so.406: cannot open shared object file: No such file or directory

As it's currently not provided by debian-base (only declared), it
only needs to be dropped from YOCTO-DEPENDS-LIST.

Signed-off-by: Alexander Herfurtner <alexander.h@variscite.com>